image: docker:stable

services:
  - docker:dind

before_script:
  - docker info

stages:
  - tests
  - build

test:
  stage: test
  only:
    - master
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  script:
    - docker run --rm ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=coverage.xml UnitTests/*.dll
  artifacts:
    when: always
    paths:
      - coverage.xml


build:
  stage: build
  only:
    - master
  before_script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest src
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  after_script:
    - docker logout ${CI_REGISTRY}
  tags: 
    - docker